---
apiVersion: v1
kind: Secret
metadata:
  name: rhdh-demo-quarkus-repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/idp-myocp/rhdh-demo-quarkus-gitops